### ISSUE TITLE
launch failed！

### ISSUE THREAD

**Issue by wanguangxi** [pietrolechthaler/UR5-Pick-and-Place-Simulation#1]
Hi， I met a problem like follows:
`roslaunch levelManager lego_world.launch
WARNING: Package name "levelManager" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "robotName_description" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
... logging to /home/one/.ros/log/50b15b34-5e80-11ed-b156-b556b4c50817/roslaunch-wan-5574.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

WARNING: Package name "levelManager" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "robotName_description" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://wan:36055/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /gazebo_ros_control/pid_gains/elbow_joint/d: 50.0
 * /gazebo_ros_control/pid_gains/elbow_joint/i: 10
 * /gazebo_ros_control/pid_gains/elbow_joint/i_clamp: 100
 * /gazebo_ros_control/pid_gains/elbow_joint/p: 10000
 * /gazebo_ros_control/pid_gains/robotiq_85_left_knuckle_joint/p: 100.0
 * /gazebo_ros_control/pid_gains/shoulder_lift_joint/d: 100.0
 * /gazebo_ros_control/pid_gains/shoulder_lift_joint/i: 10
 * /gazebo_ros_control/pid_gains/shoulder_lift_joint/i_clamp: 100
 * /gazebo_ros_control/pid_gains/shoulder_lift_joint/p: 10000
 * /gazebo_ros_control/pid_gains/shoulder_pan_joint/d: 100.0
 * /gazebo_ros_control/pid_gains/shoulder_pan_joint/i: 0.2
 * /gazebo_ros_control/pid_gains/shoulder_pan_joint/i_clamp: 10
 * /gazebo_ros_control/pid_gains/shoulder_pan_joint/p: 2500.0
 * /gazebo_ros_control/pid_gains/wrist_1_joint/d: 25.0
 * /gazebo_ros_control/pid_gains/wrist_1_joint/i: 0.2
 * /gazebo_ros_control/pid_gains/wrist_1_joint/i_clamp: 0
 * /gazebo_ros_control/pid_gains/wrist_1_joint/p: 1000.0
 * /gazebo_ros_control/pid_gains/wrist_2_joint/d: 25.0
 * /gazebo_ros_control/pid_gains/wrist_2_joint/i: 0.7
 * /gazebo_ros_control/pid_gains/wrist_2_joint/i_clamp: 5
 * /gazebo_ros_control/pid_gains/wrist_2_joint/p: 1000.0
 * /gazebo_ros_control/pid_gains/wrist_3_joint/d: 25.5
 * /gazebo_ros_control/pid_gains/wrist_3_joint/i: 0.7
 * /gazebo_ros_control/pid_gains/wrist_3_joint/i_clamp: 5
 * /gazebo_ros_control/pid_gains/wrist_3_joint/p: 1000.0
 * /gripper_controller/action_monitor_rate: 20
 * /gripper_controller/gains/robotiq_85_left_knuckle_joint/d: 0.1
 * /gripper_controller/gains/robotiq_85_left_knuckle_joint/i: 0
 * /gripper_controller/gains/robotiq_85_left_knuckle_joint/i_clamp: 0
 * /gripper_controller/gains/robotiq_85_left_knuckle_joint/p: 4
 * /gripper_controller/goal_tolerance: 0.002
 * /gripper_controller/joint: robotiq_85_left_k...
 * /gripper_controller/max_effort: 100
 * /gripper_controller/stall_timeout: 1.0
 * /gripper_controller/stall_velocity_threshold: 0.001
 * /gripper_controller/type: effort_controller...
 * /joint_state_controller/publish_rate: 125
 * /joint_state_controller/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 50.0
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /trajectory_controller/action_monitor_rate: 10
 * /trajectory_controller/constraints/elbow_joint/goal: 0.1
 * /trajectory_controller/constraints/elbow_joint/trajectory: 0.1
 * /trajectory_controller/constraints/goal_time: 0.6
 * /trajectory_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /trajectory_controller/constraints/shoulder_lift_joint/trajectory: 0.1
 * /trajectory_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /trajectory_controller/constraints/shoulder_pan_joint/trajectory: 0.1
 * /trajectory_controller/constraints/stopped_velocity_tolerance: 0.05
 * /trajectory_controller/constraints/wrist_1_joint/goal: 0.1
 * /trajectory_controller/constraints/wrist_1_joint/trajectory: 0.1
 * /trajectory_controller/constraints/wrist_2_joint/goal: 0.1
 * /trajectory_controller/constraints/wrist_2_joint/trajectory: 0.1
 * /trajectory_controller/constraints/wrist_3_joint/goal: 0.1
 * /trajectory_controller/constraints/wrist_3_joint/trajectory: 0.1
 * /trajectory_controller/joints: ['shoulder_pan_jo...
 * /trajectory_controller/state_publish_rate: 25
 * /trajectory_controller/stop_trajectory_duration: 0.5
 * /trajectory_controller/type: position_controll...
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    levelManager (levelManager/levelManager.py)
    robot_controllers (controller_manager/spawner)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    spawn_gazebo_model (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [5598]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 50b15b34-5e80-11ed-b156-b556b4c50817
WARNING: Package name "levelManager" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "robotName_description" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[rosout-1]: started with pid [5615]
started core service [/rosout]
process[gazebo-2]: started with pid [5622]
process[gazebo_gui-3]: started with pid [5627]
process[spawn_gazebo_model-4]: started with pid [5632]
process[robot_controllers-5]: started with pid [5633]
process[robot_state_publisher-6]: started with pid [5634]
process[levelManager-7]: started with pid [5635]
[ WARN] [1667814073.099875444]: link 'robotiq_coupler' material 'flat_black' undefined.
[ WARN] [1667814073.100885810]: link 'robotiq_coupler' material 'flat_black' undefined.
WARNING: Package name "levelManager" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "robotName_description" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "levelManager" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "robotName_description" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "levelManager" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "robotName_description" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "levelManager" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "robotName_description" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
[INFO] [1667814073.558426, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1667814073.566681, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
Waining gazebo service..
[ INFO] [1667814073.703495112]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1667814073.704510189]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1667814073.790957198]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1667814073.791926504]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
Warning [parser.cc:833] XML Attribute[version] in element[sdf] not defined in SDF, ignoring.
Warning [parser.cc:833] XML Attribute[version] in element[sdf] not defined in SDF, ignoring.
Warning [parser.cc:833] XML Attribute[version] in element[sdf] not defined in SDF, ignoring.
[ INFO] [1667814074.319198086]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1667814074.340283428]: Physics dynamic reconfigure ready.
[INFO] [1667814074.471848, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1667814075.256219446]: Camera Plugin: The 'robotNamespace' param did not exit
[ INFO] [1667814075.258502455]: Camera Plugin (ns = )  <tf_prefix_>, set to ""
[ INFO] [1667814075.269495430]: SetStatic service at: /link_attacher_node/setstatic
[ INFO] [1667814075.270917791]: Attach service at: /link_attacher_node/attach
[ INFO] [1667814075.271429790]: Detach service at: /link_attacher_node/detach
[ INFO] [1667814075.271472985]: Link attacher node initialized.
[INFO] [1667814075.455326, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[ERROR] [1667814075.455781567]: DeleteModel: model [X1-Y1-Z2_1] does not exist
[INFO] [1667814075.456753, 0.000000]: Waiting for service /gazebo/set_model_configuration
[ERROR] [1667814075.458058682]: DeleteModel: model [X1-Y2-Z1_1] does not exist
[INFO] [1667814075.459632, 0.000000]: temporary hack to **fix** the -J joint position option (issue #93), sleeping for 1 second to avoid race condition.
[ERROR] [1667814075.471374971]: DeleteModel: model [X1-Y2-Z2_1] does not exist
[ERROR] [1667814075.473742902]: DeleteModel: model [X1-Y2-Z2-CHAMFER_1] does not exist
[ERROR] [1667814075.475736050]: DeleteModel: model [X1-Y2-Z2-TWINFILLET_1] does not exist
[ERROR] [1667814075.478212906]: DeleteModel: model [X1-Y3-Z2_1] does not exist
[ERROR] [1667814075.480136120]: DeleteModel: model [X1-Y3-Z2-FILLET_1] does not exist
[ERROR] [1667814075.482023852]: DeleteModel: model [X1-Y4-Z1_1] does not exist
[ERROR] [1667814075.483716889]: DeleteModel: model [X1-Y4-Z2_1] does not exist
[ERROR] [1667814075.485569330]: DeleteModel: model [X2-Y2-Z2_1] does not exist
[ERROR] [1667814075.488242921]: DeleteModel: model [X2-Y2-Z2-FILLET_1] does not exist
[ INFO] [1667814075.614511046]: Loading gazebo_ros_control plugin
[ INFO] [1667814075.614626846]: Starting gazebo_ros_control plugin in namespace: /
[ INFO] [1667814075.615539848]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
[ WARN] [1667814075.733096421]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'shoulder_pan_joint'.
[ WARN] [1667814075.745633882]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'shoulder_lift_joint'.
[ WARN] [1667814075.757633154]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'elbow_joint'.
[ WARN] [1667814075.770235688]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'wrist_1_joint'.
[ WARN] [1667814075.782024807]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'wrist_2_joint'.
[ WARN] [1667814075.793172284]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'wrist_3_joint'.
[ INFO] [1667814075.809105378]: Loaded gazebo_ros_control.
[ INFO] [1667814075.821190622]: ft_sensor plugin reporting wrench values to the frame [wrist_3_link]
**[ERROR] [1667814076.011753785]: Could not load controller 'gripper_controller' because controller type 'effort_controllers/GripperActionController' does not exist.
[ERROR] [1667814076.011798092]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[Error]: select level from 1 to 4**
All done. Ready to start.
[levelManager-7] process has finished cleanly
log file: /home/one/.ros/log/50b15b34-5e80-11ed-b156-b556b4c50817/levelManager-7*.log
[INFO] [1667814076.461432, 0.000000]: Calling service /gazebo/set_model_configuration
[INFO] [1667814076.464250, 0.000000]: Set model configuration status: SetModelConfiguration: success
[ERROR] [1667814077.012107, 0.000000]: **Failed to load gripper_controller**
[spawn_gazebo_model-4] process has finished cleanly
log file: /home/one/.ros/log/50b15b34-5e80-11ed-b156-b556b4c50817/spawn_gazebo_model-4*.log

`

**Comment by wanguangxi** [comment]
Ubuntu20.04+noe-------- 原始邮件 --------发件人： Pietro Lechthaler ***@***.***>日期： 2022年11月7日周一 傍晚6:03收件人： pietrolechthaler/UR5-Pick-and-Place-Simulation ***@***.***>抄送： wgx ***@***.***>, Mention ***@***.***>主    题： Re: [pietrolechthaler/UR5-Pick-and-Place-Simulation] launch failed！ (Issue #1)
Hi @wanguangxi, which version of ROS do you have installed?

**Comment by wanguangxi** [comment]
> Hi @wanguangxi, which version of ROS do you have installed?

Hi, [pietrolechthaler](https://github.com/pietrolechthaler). I have solved this issue by install GripperActionController'

**Comment by biosbeta** [comment]
> > Hi @wanguangxi, which version of ROS do you have installed?
> 
> Hi, [pietrolechthaler](https://github.com/pietrolechthaler). I have solved this issue by install GripperActionController'

我也是遇到了相同的问题，但是安装GripperActionController之后，仍然有报错。不知道为什么run运动规划，但是机械臂就是不动。请问你有遇到这样的情况吗
报错如下
[ INFO] [1689596185.448412325]: Link attacher node initialized.
[ERROR] [1689596185.529163337]: DeleteModel: model [X1-Y1-Z2_1] does not exist
[INFO] [1689596185.529251, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[INFO] [1689596185.530335, 0.000000]: Waiting for service /gazebo/set_model_configuration
[INFO] [1689596185.531885, 0.000000]: temporary hack to **fix** the -J joint position option (issue #93), sleeping for 1 second to avoid race condition.
[ERROR] [1689596185.532621349]: DeleteModel: model [X1-Y2-Z1_1] does not exist
[ERROR] [1689596185.534660631]: DeleteModel: model [X1-Y2-Z2_1] does not exist
[ERROR] [1689596185.536846523]: DeleteModel: model [X1-Y2-Z2-CHAMFER_1] does not exist
[ERROR] [1689596185.538784214]: DeleteModel: model [X1-Y2-Z2-TWINFILLET_1] does not exist
[ERROR] [1689596185.541167694]: DeleteModel: model [X1-Y3-Z2_1] does not exist
[ERROR] [1689596185.543427820]: DeleteModel: model [X1-Y3-Z2-FILLET_1] does not exist
[ERROR] [1689596185.545691522]: DeleteModel: model [X1-Y4-Z1_1] does not exist
[ERROR] [1689596185.548006932]: DeleteModel: model [X1-Y4-Z2_1] does not exist
[ERROR] [1689596185.550081841]: DeleteModel: model [X2-Y2-Z2_1] does not exist
[ERROR] [1689596185.552105838]: DeleteModel: model [X2-Y2-Z2-FILLET_1] does not exist

**Comment by Trucle034569** [comment]
Hi, @wanguangxi. Can you show me how to fix it? Thanks
