### ISSUE TITLE
Vision and motion planning issue

### ISSUE THREAD

**Issue by Zion-Go** [pietrolechthaler/UR5-Pick-and-Place-Simulation#3]
Hello! 

I know it's hard to exactly trouble shoot my issues.. but in case..
I can run scripts but firstly when I can go to motion planning.py . The script stopped to run till 'the detection of the model'. And I started the go through the codes.
And now, the vision scripts can not run till '(waiting for the image)'. I think the cv part may have some issues during my running.
If any help and comments can be provided, Thank you very much!

Best regards,
Zion

**Comment by ShenoyVaradaraya** [comment]
did you try unpausing the gazebo simulation?

**Comment by PushpakAg** [comment]
https://github.com/pietrolechthaler/UR5-Pick-and-Place-Simulation/issues/12#issuecomment-2377573218

**Comment by Zion-Go** [comment]
> [#12 (comment)](https://github.com/pietrolechthaler/UR5-Pick-and-Place-Simulation/issues/12#issuecomment-2377573218)

Thank you!

**Comment by Zion-Go** [comment]
> did you try unpausing the gazebo simulation?

Thank you!
